sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14

cache:
  bundle: true
  directories:
    - node_modules

#install:
# - npm install

script:
  - npm install codecov nyc --no-save
  - npx nyc $(npm bin)/ava
after_script:
  - npx nyc report --reporter=text-lcov | npx codecov --token=$CODECOV_TOKEN --pipe
